### PR TITLE
읽기 어려운 문장 수정

### PR DESCRIPTION
**Pull request by woozet**
아티클 읽는 중 이해가 어려운 문장이 있어 수정해봅니다... ^^;

### CODE REVIEW

**Comment by SunnyDeng** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/patterns/pipes-and-filters.md](https://github.com/woozet/architecture-center.ko-kr/blob/live/docs/patterns/pipes-and-filters.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/ko-kr/azure/architecture/patterns/pipes-and-filters?branch=pr-ko-kr-5) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C17%5C5ae6fd2d-6385-6cce-0873-936348c664bd%5CPullRequest%5C201808170232584227-5%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=c57WskTSGp%2Fa0A8NNrLpRRf0AhYNVgnLhJ6rG2nFksI%3D&st=2018-08-17T02%3A29%3A38Z&se=2018-09-17T02%3A34%3A38Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-elcou** [comment]
안녕하세요. @woozet 님. 현재 아직 논의 중이며, 곧 결정 사항을 업데이트하겠습니다.  
	 
관심을 가져 주셔서 감사합니다. 
Microsoft C&E 로컬라이제이션 팀

**Comment by SunnyDeng** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/patterns/pipes-and-filters.md](https://github.com/woozet/architecture-center.ko-kr/blob/live/docs/patterns/pipes-and-filters.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/ko-kr/azure/architecture/patterns/pipes-and-filters?branch=pr-ko-kr-5) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C21%5C5ae6fd2d-6385-6cce-0873-936348c664bd%5CPullRequest%5C201808211442061821-5%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=EdBD%2FSiGE43C6MqVHQlld9H6qZDqOGRuBiMEgdH3L%2B4%3D&st=2018-08-21T14%3A38%3A28Z&se=2018-09-21T14%3A43%3A28Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by LisandroSu** [comment]
Hello, @woozet , 

Thank you for your feedback and suggestions.
 
This proposed file change has been accepted. The suggestion will be merged to this repository.  We will release this article on the next localization release round. 
 
Many thanks for your support.

Kind regards,

Microsoft C&E Localization Team

**Pull request merged**
